### ISSUE TITLE
After adding post, website not updated.

### ISSUE THREAD

**Issue by mandeeps708** [GreatDevelopers/greatdevelopers.github.io#4]
I added a new post here: https://github.com/GreatDevelopers/greatdevelopers.github.io/blob/master/_posts/2016-01-02-tcc-website-Inderpreet.markdown

But here: http://greatdevelopers.github.io
it's not showing the above post.
What is the problem?

**Comment by mandeeps708** [comment]
The above post included a for loop i.e. {% for posts in site.posts %}. That was conflicting with the jekyll syntax.
I removed that for now and it's working fine.

**Comment by amisha2016** [comment]
@mandeeps708 
I have not write access in github.com/GreatDevelopers/greatdevelopers.github.io due to which I have created a pull request.

**Comment by mandeeps708** [comment]
@amisha2016
That's what you're supposed to do.

BTW add some markdown magic in the file. It seems to be a plain text file.

Compare both:
1. https://raw.githubusercontent.com/amisha2016/greatdevelopers.github.io/946898188a5f0488eb0a391b17b85d419ad259cc/_posts/2016-06-11-Saturday_presentation
2. https://raw.githubusercontent.com/amisha2016/greatdevelopers.github.io/946898188a5f0488eb0a391b17b85d419ad259cc/_posts/2016-01-02-tcc-website-Inderpreet.markdown

And I think it will not render properly. Compare with other posts' code and then send the pull request again.

Thank you.

**Comment by amisha2016** [comment]
On Sun, Jun 12, 2016 at 5:58 PM, Mandeep Singh notifications@github.com
wrote:

> @amisha2016 https://github.com/amisha2016
> That's what you're supposed to do.
> 
> BTW add some markdown magic in the file. It seems to be a plain text file.
> 
> Compare both:
> 
>    1.
> 
>    https://raw.githubusercontent.com/amisha2016/greatdevelopers.github.io/946898188a5f0488eb0a391b17b85d419ad259cc/_posts/2016-06-11-Saturday_presentation
>    2.
> 
>    https://raw.githubusercontent.com/amisha2016/greatdevelopers.github.io/946898188a5f0488eb0a391b17b85d419ad259cc/_posts/2016-01-02-tcc-website-Inderpreet.markdown
> 
> And I think it will not render properly. Compare with other posts' code
> and then send the pull request again.
> 
> ​I have send the pull request again. If I have done any mistake let me
> know. ​

## 

Regards,
Amisha Budhiraja.
Gmail: amishabudhiraja96@gmail.com
Blog: https://amisha2016.wordpress.com
Gitlab: https://gitlab.com/u/Amisha2016
